### ISSUE TITLE
PYPI tarball does not include dependencies dir

### ISSUE THREAD

**Issue by MatthewZMD** [ramonhagenaars/nptyping#98]
Hey folks, is the [PYPI release](https://pypi.org/project/nptyping/#files) maintained by you too? Apparently it does not contain `dependencies/build-requirements.txt`, using the PYPI release will fail `setup.py` that explicitly required `dependencies/build-requirements.txt`

```
FileNotFoundError: [Errno 2] No such file or directory: '.../nptyping-2.3.1/dependencies/build-requirements.txt'
```

**Comment by ramonhagenaars** [comment]
Hi @MatthewZMD ! Thanks for pointing this out, this doesn't seem right.

**Comment by rhurlin** [comment]
Any chance to get a new PyPi version with the dependencies directory in the near future?

BTW, it would be nice if this would happen for the tests directory as well, since systems like FreeBSD use the tests in their ports and packages. I'm preparing a port for nptyping and would like to integrate the tests ;)

Thank you for your understanding!
Rainer

**Comment by ramonhagenaars** [comment]
Hi folks.

Starting with release `2.5.0` (in the making), the distribution will include the requirement files, tests, etc.

**Comment by rhurlin** [comment]
Hi @ramonhagenaars,
Many thanks! Really appreciated. I will use it in my next packaging on FreeBSD, after 2.5.0 is released.

**Comment by ramonhagenaars** [comment]
With [v2.5.0](https://github.com/ramonhagenaars/nptyping/releases/tag/v2.5.0) this issue should be resolved. Please let me know if you encounter any problems still.
